CC=gcc
CFLAGS=-Wall -g
LIBS=

all: bubblesort.o quicksort.o mergesort_.o insertionsort.o shellsort.o

bubblesort.o: bubblesort.c

quicksort.o: quicksort.c

mergesort_.o: mergesort_.c

insertionsort.o: insertionsort.c

shellsort.o: shellsort.c

clean:
	rm -f bubblesort.o
	rm -f quicksort.o
	rm -f mergesort_.o
	rm -f insertionsort.o
	rm -f shellsort.o
