# Project: celg25112006
# Makefile created by Dev-C++ 4.9.9.2

CPP  = g++
CC   = gcc
WINDRES = 
RES  = 
OBJ  = zollen.o entrada.o controle.o fdlf.o fluxos.o matrizes.o potencia.o prepara.o saida.o estado.o $(RES)
LINKOBJ  = zollen.o entrada.o controle.o fdlf.o fluxos.o matrizes.o potencia.o prepara.o saida.o estado.o $(RES)
LIBS =  -lm 
INCS =  
CXXINCS =  
BIN  = celg25112006
CXXFLAGS = $(CXXINCS)  
CFLAGS = $(INCS)  
RM = rm -f

.PHONY: all all-before all-after clean clean-custom

all: all-before celg25112006 all-after


clean: clean-custom
	${RM} $(OBJ) $(BIN)

$(BIN): $(OBJ)
	$(CC) $(LINKOBJ) -o "celg25112006" $(LIBS)

zollen.o: zollen.c
	$(CC) -c zollen.c -o zollen.o $(CFLAGS)

entrada.o: entrada.c
	$(CC) -c entrada.c -o entrada.o $(CFLAGS)

controle.o: controle.c
	$(CC) -c controle.c -o controle.o $(CFLAGS)

fdlf.o: fdlf.c
	$(CC) -c fdlf.c -o fdlf.o $(CFLAGS)

fluxos.o: fluxos.c
	$(CC) -c fluxos.c -o fluxos.o $(CFLAGS)

matrizes.o: matrizes.c
	$(CC) -c matrizes.c -o matrizes.o $(CFLAGS)

potencia.o: potencia.c
	$(CC) -c potencia.c -o potencia.o $(CFLAGS)

prepara.o: prepara.c
	$(CC) -c prepara.c -o prepara.o $(CFLAGS)

saida.o: saida.c
	$(CC) -c saida.c -o saida.o $(CFLAGS)

estado.o: estado.c
	$(CC) -c estado.c -o estado.o $(CFLAGS)
