/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class JFrameEx */

#ifndef _Included_JFrameEx
#define _Included_JFrameEx
#ifdef __cplusplus
extern "C" {
#endif
#undef JFrameEx_FOCUS_TRAVERSABLE_UNKNOWN
#define JFrameEx_FOCUS_TRAVERSABLE_UNKNOWN 0L
#undef JFrameEx_FOCUS_TRAVERSABLE_DEFAULT
#define JFrameEx_FOCUS_TRAVERSABLE_DEFAULT 1L
#undef JFrameEx_FOCUS_TRAVERSABLE_SET
#define JFrameEx_FOCUS_TRAVERSABLE_SET 2L
#undef JFrameEx_TOP_ALIGNMENT
#define JFrameEx_TOP_ALIGNMENT 0.0f
#undef JFrameEx_CENTER_ALIGNMENT
#define JFrameEx_CENTER_ALIGNMENT 0.5f
#undef JFrameEx_BOTTOM_ALIGNMENT
#define JFrameEx_BOTTOM_ALIGNMENT 1.0f
#undef JFrameEx_LEFT_ALIGNMENT
#define JFrameEx_LEFT_ALIGNMENT 0.0f
#undef JFrameEx_RIGHT_ALIGNMENT
#define JFrameEx_RIGHT_ALIGNMENT 1.0f
#undef JFrameEx_serialVersionUID
#define JFrameEx_serialVersionUID -7644114512714619750i64
#undef JFrameEx_serialVersionUID
#define JFrameEx_serialVersionUID 4613797578919906343i64
#undef JFrameEx_INCLUDE_SELF
#define JFrameEx_INCLUDE_SELF 1L
#undef JFrameEx_SEARCH_HEAVYWEIGHTS
#define JFrameEx_SEARCH_HEAVYWEIGHTS 1L
#undef JFrameEx_OPENED
#define JFrameEx_OPENED 1L
#undef JFrameEx_serialVersionUID
#define JFrameEx_serialVersionUID 4497834738069338734i64
#undef JFrameEx_DEFAULT_CURSOR
#define JFrameEx_DEFAULT_CURSOR 0L
#undef JFrameEx_CROSSHAIR_CURSOR
#define JFrameEx_CROSSHAIR_CURSOR 1L
#undef JFrameEx_TEXT_CURSOR
#define JFrameEx_TEXT_CURSOR 2L
#undef JFrameEx_WAIT_CURSOR
#define JFrameEx_WAIT_CURSOR 3L
#undef JFrameEx_SW_RESIZE_CURSOR
#define JFrameEx_SW_RESIZE_CURSOR 4L
#undef JFrameEx_SE_RESIZE_CURSOR
#define JFrameEx_SE_RESIZE_CURSOR 5L
#undef JFrameEx_NW_RESIZE_CURSOR
#define JFrameEx_NW_RESIZE_CURSOR 6L
#undef JFrameEx_NE_RESIZE_CURSOR
#define JFrameEx_NE_RESIZE_CURSOR 7L
#undef JFrameEx_N_RESIZE_CURSOR
#define JFrameEx_N_RESIZE_CURSOR 8L
#undef JFrameEx_S_RESIZE_CURSOR
#define JFrameEx_S_RESIZE_CURSOR 9L
#undef JFrameEx_W_RESIZE_CURSOR
#define JFrameEx_W_RESIZE_CURSOR 10L
#undef JFrameEx_E_RESIZE_CURSOR
#define JFrameEx_E_RESIZE_CURSOR 11L
#undef JFrameEx_HAND_CURSOR
#define JFrameEx_HAND_CURSOR 12L
#undef JFrameEx_MOVE_CURSOR
#define JFrameEx_MOVE_CURSOR 13L
#undef JFrameEx_NORMAL
#define JFrameEx_NORMAL 0L
#undef JFrameEx_ICONIFIED
#define JFrameEx_ICONIFIED 1L
#undef JFrameEx_MAXIMIZED_HORIZ
#define JFrameEx_MAXIMIZED_HORIZ 2L
#undef JFrameEx_MAXIMIZED_VERT
#define JFrameEx_MAXIMIZED_VERT 4L
#undef JFrameEx_MAXIMIZED_BOTH
#define JFrameEx_MAXIMIZED_BOTH 6L
#undef JFrameEx_serialVersionUID
#define JFrameEx_serialVersionUID 2673458971256075116i64
#undef JFrameEx_EXIT_ON_CLOSE
#define JFrameEx_EXIT_ON_CLOSE 3L
/*
 * Class:     JFrameEx
 * Method:    getHWND
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_JFrameEx_getHWND
  (JNIEnv *, jobject);

/*
 * Class:     JFrameEx
 * Method:    setHook
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_JFrameEx_setHook
  (JNIEnv *, jobject, jint);

/*
 * Class:     JFrameEx
 * Method:    resetHook
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_JFrameEx_resetHook
  (JNIEnv *, jobject, jint);

/*
 * Class:     JFrameEx
 * Method:    initRawInput
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_JFrameEx_initRawInput
  (JNIEnv *, jobject);

/*
 * Class:     JFrameEx
 * Method:    showCursor
 * Signature: (Z)I
 */
JNIEXPORT jint JNICALL Java_JFrameEx_showCursor
  (JNIEnv *, jobject, jboolean);

/*
 * Class:     JFrameEx
 * Method:    setCursorPos
 * Signature: (II)Z
 */
JNIEXPORT jboolean JNICALL Java_JFrameEx_setCursorPos
  (JNIEnv *, jobject, jint, jint);

/*
 * Class:     JFrameEx
 * Method:    getLastError
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_JFrameEx_getLastError
  (JNIEnv *, jobject);

/*
 * Class:     JFrameEx
 * Method:    getCursorPos
 * Signature: ()Ljava/awt/Point;
 */
JNIEXPORT jobject JNICALL Java_JFrameEx_getCursorPos
  (JNIEnv *, jobject);

/*
 * Class:     JFrameEx
 * Method:    getMouseIds
 * Signature: ()[I
 */
JNIEXPORT jintArray JNICALL Java_JFrameEx_getMouseIds
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
