/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class JFrameEx_PointerGlassPane */

#ifndef _Included_JFrameEx_PointerGlassPane
#define _Included_JFrameEx_PointerGlassPane
#ifdef __cplusplus
extern "C" {
#endif
#undef JFrameEx_PointerGlassPane_FOCUS_TRAVERSABLE_UNKNOWN
#define JFrameEx_PointerGlassPane_FOCUS_TRAVERSABLE_UNKNOWN 0L
#undef JFrameEx_PointerGlassPane_FOCUS_TRAVERSABLE_DEFAULT
#define JFrameEx_PointerGlassPane_FOCUS_TRAVERSABLE_DEFAULT 1L
#undef JFrameEx_PointerGlassPane_FOCUS_TRAVERSABLE_SET
#define JFrameEx_PointerGlassPane_FOCUS_TRAVERSABLE_SET 2L
#undef JFrameEx_PointerGlassPane_TOP_ALIGNMENT
#define JFrameEx_PointerGlassPane_TOP_ALIGNMENT 0.0f
#undef JFrameEx_PointerGlassPane_CENTER_ALIGNMENT
#define JFrameEx_PointerGlassPane_CENTER_ALIGNMENT 0.5f
#undef JFrameEx_PointerGlassPane_BOTTOM_ALIGNMENT
#define JFrameEx_PointerGlassPane_BOTTOM_ALIGNMENT 1.0f
#undef JFrameEx_PointerGlassPane_LEFT_ALIGNMENT
#define JFrameEx_PointerGlassPane_LEFT_ALIGNMENT 0.0f
#undef JFrameEx_PointerGlassPane_RIGHT_ALIGNMENT
#define JFrameEx_PointerGlassPane_RIGHT_ALIGNMENT 1.0f
#undef JFrameEx_PointerGlassPane_serialVersionUID
#define JFrameEx_PointerGlassPane_serialVersionUID -7644114512714619750i64
#undef JFrameEx_PointerGlassPane_serialVersionUID
#define JFrameEx_PointerGlassPane_serialVersionUID 3258134673799526197i64
#ifdef __cplusplus
}
#endif
#endif
